export const testIds = {
  appShell: 'app-shell',
  pythonRestartButton: 'python-restart-button',
  pythonStatusBanner: 'python-status-banner',
  shellLogo: 'shell-logo',
  shellLocaleSwitch: 'shell-locale-switch',
  shellHomeButton: 'shell-home-button',
  shellStatus: 'shell-status',
  homePage: 'home-page',
  homePrimaryAction: 'home-primary-action',
  homeLogsAction: 'home-logs-action',
  placeholderPage: 'placeholder-page',
  notFoundPage: 'not-found-page',
  boundaryPage: 'error-boundary-page',
  toastViewport: 'toast-viewport',
  plotlyChart: 'plotly-chart',
  lineChart: 'line-chart',
  heatmapChart: 'heatmap-chart',
  imagePreview: 'image-preview',

  // Business components / 业务组件
  fileDialogButton: 'file-dialog-button',
  fileDialogTrigger: 'file-dialog-trigger',
  fileDialogPath: 'file-dialog-path',
  fileDialogClear: 'file-dialog-clear',

  geometryForm: 'geometry-form',
  geometryModePoni: 'geometry-mode-poni',
  geometryModeManual: 'geometry-mode-manual',
  geometryPoniInput: 'geometry-poni-input',
  geometryPixel1: 'geometry-pixel1',
  geometryDistance: 'geometry-distance',
  geometryWavelength: 'geometry-wavelength',
  geometryCenterX: 'geometry-center-x',
  geometryCenterY: 'geometry-center-y',

  maskBuilderForm: 'mask-builder-form',
  maskValueRangeMin: 'mask-value-range-min',
  maskValueRangeMax: 'mask-value-range-max',
  maskDeadPixelThreshold: 'mask-dead-pixel-threshold',
  maskCustomFile: 'mask-custom-file',

  polarizationForm: 'polarization-form',
  polarizationEnabled: 'polarization-enabled',
  polarizationSlider: 'polarization-slider',
  polarizationValue: 'polarization-value',

  advancedOptionsForm: 'advanced-options-form',
  advancedNptRad: 'advanced-npt-rad',
  advancedNptAzim: 'advanced-npt-azim',
  advancedRadialMin: 'advanced-radial-min',
  advancedRadialMax: 'advanced-radial-max',
  advancedUnit: 'advanced-unit',
  advancedSolidAngle: 'advanced-solid-angle',
  advancedAlgorithm: 'advanced-algorithm',
  advancedIntegrator: 'advanced-integrator',

  taskProgressBar: 'task-progress-bar',
  taskProgressPercent: 'task-progress-percent',
  taskProgressTrack: 'task-progress-track',
  taskProgressCancel: 'task-progress-cancel',

  exportDialog: 'export-dialog',
  exportFormatSelect: 'export-format-select',
  exportExecute: 'export-execute',

  resultSummary: 'result-summary',
  resultTotal: 'result-total',
  resultSuccess: 'result-success',
  resultFailed: 'result-failed',
  resultElapsed: 'result-elapsed',

  // Viewer page / 查看器页面
  viewerPage: 'viewer-page',
  viewerDatasetSelect: 'viewer-dataset-select',
  viewerChannelSelect: 'viewer-channel-select',
  viewerFrameSlider: 'viewer-frame-slider',
  viewerColormapSelect: 'viewer-colormap-select',
  viewerLogToggle: 'viewer-log-toggle',
  viewerClimMin: 'viewer-clim-min',
  viewerClimMax: 'viewer-clim-max',
  viewerDpiSlider: 'viewer-dpi-slider',
  viewerExportJsonBtn: 'viewer-export-json-btn',
  viewerError: 'viewer-error',
  viewerDisplay: 'viewer-display',
  viewerThumbnailStrip: 'viewer-thumbnail-strip',
  thumbnailStrip: 'thumbnail-strip',
  viewerStats: 'viewer-stats',
  viewerFullImage: 'viewer-full-image',
  viewerAnalysisToggle: 'viewer-analysis-toggle',
  viewerHeatmapSection: 'viewer-heatmap-section',
  viewerFrameNav: 'viewer-frame-nav',

  // Integrate Azimuth page / 方位角积分页面
  integrateAzimuthPage: 'integrate-azimuth-page',
  azimuthRadialUnit: 'azimuth-radial-unit',
  azimuthRadialMin: 'azimuth-radial-min',
  azimuthRadialMax: 'azimuth-radial-max',
  azimuthChiUnitDeg: 'azimuth-chi-unit-deg',
  azimuthChiUnitRad: 'azimuth-chi-unit-rad',
  azimuthAzimuthMin: 'azimuth-azimuth-min',
  azimuthAzimuthMax: 'azimuth-azimuth-max',
  azimuthNpt: 'azimuth-npt',
  azimuthNptRad: 'azimuth-npt-rad',
  azimuthRunBtn: 'azimuth-run-btn',
  azimuthChart: 'azimuth-chart',
  azimuthExport: 'azimuth-export',

  // Integrate 1D page / 1D 积分页面
  integrate1dPage: 'integrate-1d-page',
  integrate1dFileInput: 'integrate-1d-file-input',
  integrate1dFileClear: 'integrate-1d-file-clear',
  integrate1dRunBtn: 'integrate-1d-run-btn',
  integrate1dResult: 'integrate-1d-result',
  integrate1dError: 'integrate-1d-error',
  integrate1dExport: 'integrate-1d-export',

  // CAKE integration page / CAKE 积分页面
  integrateCakePage: 'integrate-cake-page',
  cakeAzimuthMin: 'cake-azimuth-min',
  cakeAzimuthMax: 'cake-azimuth-max',
  cakeFileInput: 'cake-file-input',
  cakeRunButton: 'cake-run-button',

  // Fiber integration page / 纤维积分页面
  fiberPage: 'fiber-page',
  fiberFileInput: 'fiber-file-input',
  fiberFileName: 'fiber-file-name',
  fiberRot1: 'fiber-rot1',
  fiberRot2: 'fiber-rot2',
  fiberRot3: 'fiber-rot3',
  fiberOrientation: 'fiber-orientation',
  fiberIncidentAngle: 'fiber-incident-angle',
  fiberTiltAngle: 'fiber-tilt-angle',
  fiberUnitIp: 'fiber-unit-ip',
  fiberUnitOop: 'fiber-unit-oop',
  fiberAutoRange: 'fiber-auto-range',
  fiberIpMin: 'fiber-ip-min',
  fiberIpMax: 'fiber-ip-max',
  fiberOopMin: 'fiber-oop-min',
  fiberOopMax: 'fiber-oop-max',
  fiberNptIp: 'fiber-npt-ip',
  fiberNptOop: 'fiber-npt-oop',
  fiberSolidAngle: 'fiber-solid-angle',
  fiberRunBtn: 'fiber-run-btn',
  fiberError: 'fiber-error',
  fiberHeatmap: 'fiber-heatmap',
  fiberTargetOop: 'fiber-target-oop',
  fiberTargetIp: 'fiber-target-ip',
  fiberHProfile: 'fiber-h-profile',
  fiberVProfile: 'fiber-v-profile',
  fiberExport: 'fiber-export',

  // PNG Generate page / PNG 生成页
  pngGeneratePage: 'png-generate-page',
  pngGenerateRecursive: 'png-generate-recursive',
  pngGenerateLoadJson: 'png-generate-load-json',
  pngGenerateSaveJson: 'png-generate-save-json',
  pngGenerateColormap: 'png-generate-colormap',
  pngGenerateLog: 'png-generate-log',
  pngGenerateClimMin: 'png-generate-clim-min',
  pngGenerateClimMax: 'png-generate-clim-max',
  pngGenerateDpi: 'png-generate-dpi',
  pngGenerateAxes: 'png-generate-axes',
  pngGenerateColorbar: 'png-generate-colorbar',
  pngGenerateScanBtn: 'png-generate-scan-btn',
  pngGenerateScanInfo: 'png-generate-scan-info',
  pngGenerateRunBtn: 'png-generate-run-btn',
  pngGenerateError: 'png-generate-error',

  // H5 Convert page / H5 格式转换页
  h5convertPage: 'h5convert-page',
  h5convertSourceDir: 'h5convert-source-dir',
  h5convertOutputDir: 'h5convert-output-dir',
  h5convertSuffix: 'h5convert-suffix',
  h5convertScanBtn: 'h5convert-scan-btn',
  h5convertScanInfo: 'h5convert-scan-info',
  h5convertDatasetTable: 'h5convert-dataset-table',
  h5convertDatasetCheck: 'h5convert-dataset-check',
  h5convertFormat: 'h5convert-format',
  h5convertStartBtn: 'h5convert-start-btn',

  // H5 Extract page / H5 文件提取页
  h5extractPage: 'h5extract-page',
  h5extractSourceDir: 'h5extract-source-dir',
  h5extractTargetDir: 'h5extract-target-dir',
  h5extractSuffix: 'h5extract-suffix',
  h5extractPrependFolder: 'h5extract-prepend-folder',
  h5extractPrefix: 'h5extract-prefix',
  h5extractConflictPolicy: 'h5extract-conflict-policy',
  h5extractStartBtn: 'h5extract-start-btn',
} as const
