#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""test_poni_parse.py — Tests for reverse-reading geometry from .poni files.

Covers `parse_poni_file` normalization, in particular the v0.2.5 additions:
pixel size / max_shape / orientation recovered from the `Detector_config`
JSON blob of generic `Detector:` files (pyFAI-native and X-FAIS-exported).
"""

import pytest

from python.services.poni_importer import export_to_poni, parse_poni_file


def _write_poni(tmp_path, lines, name="test.poni"):
    path = tmp_path / name
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return str(path)


def test_parse_pyfai_native_poni(tmp_path):
    """A pyFAI-native file (registry detector, SI units) parses to SI values."""
    path = _write_poni(tmp_path, [
        "# Nota: C-Order, 1 refers to the Y axis, 2 to the X axis",
        "Distance: 0.1823",
        "Poni1: 0.0123",
        "Poni2: 0.0456",
        "Rot1: 0.001",
        "Rot2: -0.002",
        "Rot3: 0.0",
        "Wavelength: 1.5406e-10",
        "Detector: Pilatus1M",
        'Detector_config: {"orientation": 3}',
    ])
    data = parse_poni_file(path)
    assert data is not None
    assert data["distance"] == pytest.approx(0.1823)
    assert data["wavelength"] == pytest.approx(1.5406e-10)
    assert data["poni1"] == pytest.approx(0.0123)
    assert data["poni2"] == pytest.approx(0.0456)
    assert data["rot1"] == pytest.approx(0.001)
    assert data["detector_name"] == "Pilatus1M"
    # Pixel size falls back to the pyFAI registry entry (Pilatus = 172 µm).
    # 像素尺寸回退到 pyFAI 注册表（Pilatus = 172 µm）。
    assert data["pixel_size"] == pytest.approx(172e-6, rel=1e-3)
    assert data["orientation"] == 3


def test_parse_generic_detector_config(tmp_path):
    """Generic `Detector:` config JSON provides pixel size / shape / orientation."""
    path = _write_poni(tmp_path, [
        "# PONI file generated by X-FAIS",
        "Distance: 0.1",
        "Wavelength: 1.5418e-10",
        "PixelSize: 1.72e-04, 1.72e-04",
        "Poni1: 0.0384",
        "Poni2: 0.0512",
        "Rot1: 0.0",
        "Rot2: 0.0",
        "Rot3: 0.0",
        "Detector: Detector",
        'Detector_config: {"pixel1": 7.5e-05, "pixel2": 7.5e-05, "max_shape": [1062, 1028], "orientation": 3}',
    ])
    data = parse_poni_file(path)
    assert data is not None
    # Explicit PixelSize line wins over Detector_config. / 显式 PixelSize 行优先。
    assert data["pixel_size"] == pytest.approx(1.72e-04)
    assert data["detector_shape"] == [1062, 1028]
    assert data["orientation"] == 3


def test_parse_detector_config_supplies_missing_pixel(tmp_path):
    """No PixelSize line → pixel1/pixel2 come from Detector_config."""
    path = _write_poni(tmp_path, [
        "Distance: 0.2",
        "Wavelength: 1.54e-10",
        "Poni1: 0.05",
        "Poni2: 0.06",
        "Detector: Detector",
        'Detector_config: {"pixel1": 1.72e-4, "pixel2": 1.72e-4}',
    ])
    data = parse_poni_file(path)
    assert data is not None
    assert data["pixel_size"] == pytest.approx(1.72e-4)


def test_round_trip_export_then_parse(tmp_path):
    """export → parse restores the geometry (incl. custom label + shape)."""
    poni_data = dict(
        distance=0.1, wavelength=1.5418e-10, pixel_size=75e-6,
        poni1=0.0384, poni2=0.0384, rot1=0.0, rot2=0.0, rot3=0.0,
        detector_name="Homemade CCD",
        detector_shape=[512, 512],
    )
    out = str(tmp_path / "roundtrip.poni")
    export_to_poni(poni_data, out)
    parsed = parse_poni_file(out)
    assert parsed is not None
    assert parsed["distance"] == pytest.approx(0.1)
    assert parsed["wavelength"] == pytest.approx(1.5418e-10)
    assert parsed["pixel_size"] == pytest.approx(75e-6)
    assert parsed["poni1"] == pytest.approx(0.0384)
    assert parsed["detector_shape"] == [512, 512]
    assert parsed["detector_label"] == "Homemade CCD"


def test_parse_missing_file_returns_none(tmp_path):
    assert parse_poni_file(str(tmp_path / "nope.poni")) is None


def test_parse_gbk_encoded_poni(tmp_path):
    """Official pyFAI writes .poni in the Windows locale encoding — a file
    calibrated on a Chinese-locale machine carries GBK bytes in comments
    (e.g. `# Image: .../元数据/...`). UTF-8-only reading raised
    UnicodeDecodeError → "Failed to parse PONI file"."""
    path = tmp_path / "gbk.poni"
    content = "\n".join([
        "# Nota: C-Order, 1 refers to the Y axis, 2 to the X axis",
        "poni_version: 2.1",
        "Detector: Pilatus300k",
        'Detector_config: {"pixel1": 0.000172, "pixel2": 0.000172, "orientation": 3}',
        "Distance: 0.12861543804261374",
        "Poni1: 0.09588260434412532",
        "Poni2: 0.020278122331307574",
        "Rot1: 0.0",
        "Rot2: 0.0",
        "Rot3: 0.0",
        "Wavelength: 1.5418e-10",
        "# Calibrant: PP",
        "# Image: fabio:///D:/project/waxs/20260910/元数据/20260910_0_00101.edf",
    ]) + "\n"
    path.write_bytes(content.encode("gbk"))
    data = parse_poni_file(str(path))
    assert data is not None
    assert data["distance"] == pytest.approx(0.12861543804261374)
    assert data["wavelength"] == pytest.approx(1.5418e-10)
    assert data["poni1"] == pytest.approx(0.09588260434412532)
    assert data["poni2"] == pytest.approx(0.020278122331307574)
    assert data["detector_name"] == "Pilatus300k"
    assert data["pixel_size"] == pytest.approx(172e-6, rel=1e-3)
    assert data["orientation"] == 3


def test_parse_unit_suffix_poni(tmp_path):
    """pyFAI ≥2024 may append SI units to values ("0.1823 m", "0.001 rad")."""
    path = _write_poni(tmp_path, [
        "Distance: 0.1823 m",
        "Poni1: 0.0123 m",
        "Poni2: 0.0456 m",
        "Rot1: 0.001 rad",
        "Rot2: -0.002 rad",
        "Rot3: 0.0 rad",
        "Wavelength: 1.5406e-10 m",
        "Detector: Pilatus1M",
        'Detector_config: {"orientation": 3}',
    ])
    data = parse_poni_file(path)
    assert data is not None
    assert data["distance"] == pytest.approx(0.1823)
    assert data["wavelength"] == pytest.approx(1.5406e-10)
    assert data["poni1"] == pytest.approx(0.0123)
    assert data["poni2"] == pytest.approx(0.0456)
    assert data["rot1"] == pytest.approx(0.001)
    assert data["rot2"] == pytest.approx(-0.002)


def test_parse_invalid_detector_config_is_tolerated(tmp_path):
    """A malformed Detector_config JSON must not crash the parser."""
    path = _write_poni(tmp_path, [
        "Distance: 0.1",
        "Wavelength: 1.5e-10",
        "Detector: Detector",
        "Detector_config: {not valid json",
    ])
    data = parse_poni_file(path)
    assert data is not None
    assert "pixel_size" not in data or data["pixel_size"] > 0
